import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useSession, signIn, signOut } from "next-auth/react";
import { useState } from "react";
import { useEffect } from "react";

export default function Home() {
  const { data } = useSession();

  const [user, setUser] = useState(null);

  useEffect(() => {
    if (data?.access_token) {
      fetch("http://localhost:8000/user", {
        // assign the token as bearer token on your request headers
        headers: {
          Authorization: `Bearer ${data?.access_token}`,
        },
      })
        .then((res) => res.json())
        .then((data) => {
          setUser(data);
        });
    }
  }, [data]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {data ? (
          <button onClick={() => signOut()}>Log out</button>
        ) : (
          <button onClick={() => signIn()}>Sign In</button>
        )}
        <h1 className={styles.title}>
          Welcome <strong>{user?.user}</strong>
        </h1>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
